#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Application1.Resource", IsApplication=true)]

namespace Application1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int aButton = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int abc = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int bButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int footer = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int guess = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int kanji = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int pager = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int shark = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int submit = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int text = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int type = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int StudyVocab = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int demo_collection = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int demo_external_activity = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int first = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int helloButtonText = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int helloLabelText = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int hello_world = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int kanji = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int last = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
